---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-check
  namespace: default
  annotations:
    kapp.k14s.io/nonce: ""
    kapp.k14s.io/update-strategy: fallback-on-replace
    kapp.k14s.io/change-rule: "upsert after upserting redis-primary"
    kapp.k14s.io/change-rule.1: "upsert after upserting redis-replica"
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 30
  template:
    metadata:
      name: sync-check
      annotations:
        kapp.k14s.io/deploy-logs: ""
    spec:
      containers:
      - name: sync-check
        image: redis
        command:
        - /bin/sh
        - -exc
        - |
          primary="-h redis-primary -p 6379"
          replica="-h redis-replica -p 6379"

          redis-cli $primary ping 2>&1
          redis-cli $replica ping 2>&1
          redis-cli $replica info 2>&1 | grep -A10 Replication

          redis-cli $primary set key val 2>&1
          sleep 2
          redis-cli $replica get key 2>&1
          result=$(redis-cli $replica get key 2>&1)

          if [ "x$result" != "xval" ]; then
            echo "Expected replica to be synced to primary"
            exit 1
          fi
      restartPolicy: Never
