---
apiVersion: batch/v1
kind: Job
metadata:
  name: successful-job
  namespace: default
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  backoffLimit: 2
  template:
    metadata:
      name: successful-job
      annotations:
        kapp.k14s.io/deploy-logs: "for-new-or-existing"
    spec:
      containers:
      - name: successful-job
        image: busybox
        command: ["/bin/sh", "-c", "date; sleep 11; echo DONE"]
      restartPolicy: Never
