---
apiVersion: install.package.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: simple-package-repository
spec:
  # Here we are fetching a list of packages from a docker registry. This reference
  # points to an imgpkg bundle, which is our recommended way of storing a package
  # repository
  fetch:
    imgpkgBundle:
      # This image was create by running `imgpkg push -b <repo> -f repo`. The resulting
      # image will contain the packages within the packages folder and, by adding this repo to the cluster,
      # those packages will also be available for installation.
      image: index.docker.io/k8slt/demo-repo@sha256:edc1bfd1317c6f63b7816a6d02ce0bfbe75214946887783e4d0c21e360248308
