apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
spec:
  fetch:
  - git:
      url: https://github.com/k14s/k8s-simple-app-example
      ref: origin/master
      subPath: config-step-2-template
  template:
  - ytt: {}
  deploy:
  - kapp: {}
