---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:
#! It seems that caBundle is automatically populated
- path: [webhooks, {allIndexes: true}, clientConfig, caBundle]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration

#! Managed by HPAs, hence prefer from existing resource
- path: [spec, replicas]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Deployment
      namespace: istio-system
      name: istio-telemetry
  - kindNamespaceNameMatcher:
      kind: Deployment
      namespace: istio-system
      name: istio-policy
  - kindNamespaceNameMatcher:
      kind: Deployment
      namespace: istio-system
      name: istio-ingressgateway
  - kindNamespaceNameMatcher:
      kind: Deployment
      namespace: istio-system
      name: istio-egressgateway
  - kindNamespaceNameMatcher:
      kind: Deployment
      namespace: istio-system
      name: istio-pilot
