#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata":{"name":"installedpackages.install.package.carvel.dev"}})
---
metadata:
  #@overlay/remove
  creationTimestamp: null
  #@overlay/remove
  annotations:
spec:
  validation:
    openAPIV3Schema:
      properties:
        #@overlay/remove
        metadata:
#@overlay/remove
status:

#@overlay/match by=overlay.subset({"metadata":{"name":"packagerepositories.install.package.carvel.dev"}})
---
metadata:
  #@overlay/remove
  creationTimestamp: null
  #@overlay/remove
  annotations:
spec:
  validation:
    openAPIV3Schema:
      properties:
        #@overlay/remove
        metadata:
#@overlay/remove
status:

#@overlay/match by=overlay.subset({"metadata":{"name":"apps.kappctrl.k14s.io"}})
---
metadata:
  #@overlay/remove
  creationTimestamp: null
  #@overlay/remove
  annotations:
spec:
  validation:
    openAPIV3Schema:
      properties:
        #@overlay/remove
        metadata:
#@overlay/remove
status:
