#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapp-controller
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels:
      app: kapp-controller
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: kapp-controller
    spec:
      serviceAccount: kapp-controller-sa
      containers:
      - name: kapp-controller
        image: kapp-controller
        env:
        - name: KAPPCTRL_MEM_TMP_DIR
          value: /etc/kappctrl-mem-tmp
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
        volumeMounts:
        - name: template-fs
          mountPath: /etc/kappctrl-mem-tmp
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
          fsGroup: 3000
      volumes:
      - name: template-fs
        emptyDir:
          #! https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
          medium: Memory
