
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: internalpackages.install.package.carvel.dev
spec:
  group: install.package.carvel.dev
  names:
    kind: InternalPackage
    listKind: InternalPackageList
    plural: internalpackages
    singular: internalpackage
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
