apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: concourse
  namespace: default
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - helmChart:
      name: stable/concourse
  template:
  - helmTemplate:
      valuesFrom:
      - secretRef:
          name: concourse-values
  - ytt:
      #! helm inserts comments before each doc, ignore them
      ignoreUnknownComments: true
      inline:
        paths:
          scale-up.yml: |
            #@ load("@ytt:overlay", "overlay")

            #@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name": "concourse-web"}})
            ---
            apiVersion: apps/v1 #! change from extensions/v1beta1 since it's deprecated
            spec:
              #@overlay/match expects=0
              selector:
                matchLabels:
                  app: concourse-web

            #@overlay/match by=overlay.subset({"kind":"StatefulSet", "metadata":{"name": "concourse-worker"}})
            ---
            apiVersion: apps/v1 #! change from extensions/v1beta1 since it's deprecated
            spec:
              #@overlay/match expects=0
              selector:
                matchLabels:
                  app: concourse-worker

            #@overlay/match by=overlay.subset({"kind":"StatefulSet", "metadata":{"name": "concourse-postgresql"}})
            ---
            apiVersion: apps/v1 #! change from apps/v1beta2 since it's deprecated
  deploy:
  - kapp:
      delete:
        rawOptions: ["--apply-ignored=true"]
---
apiVersion: v1
kind: Secret
metadata:
  name: concourse-values
  namespace: default
stringData:
  data.yml: |
    concourse:
      web:
        externalUrl: http://concourse-web.default.svc.cluster.local:8080
        replicas: 3
