apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: consul
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - image:
      url: dkalinin/consul-helm
  template:
  - helmTemplate: {}
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          fix.yml: |
            #@ load("@ytt:overlay", "overlay")

            #@overlay/match by=overlay.subset({"kind":"Pod", "metadata":{"name": "consul-consul-test"}})
            #@overlay/remove
            ---

            #! mark PVCs as owned by kapp so they will deleted successfully
            #@overlay/match by=overlay.subset({"kind":"StatefulSet", "metadata":{"name": "consul-consul-server"}})
            ---
            spec:
              volumeClaimTemplates:
              #@overlay/match by=overlay.subset({"metadata":{"name": "data-default"}})
              - metadata:
                  #@overlay/match missing_ok=True
                  annotations:
                    #@overlay/match expects=0
                    kapp.k14s.io/owned-for-deletion: ""

            #! Not sure why there was cluster level resources
            #@overlay/match by=overlay.subset({"kind": "ClusterRole"}),expects=2
            #@overlay/remove
            ---
            #@overlay/match by=overlay.subset({"kind": "ClusterRoleBinding"}),expects=2
            #@overlay/remove
            ---
  deploy:
  - kapp: {}
