apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cue-app
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - inline:
      paths:
        app.cue: |
            package main

            apiVersion: "v1"
            kind:       "List"
            items: [_service, _deployment]

            _labels: [string]: string
            _labels: app:      string

            _metadata: {
                name:       string
                namespace?: string
                labels:     _labels
                annotations?: [string]: string
            }

            _service: {
                apiVersion: "v1"
                kind:       "Service"
                metadata:   _metadata
                spec: {
                    ports: [{
                        port:       int | *80
                        targetPort: int | *80
                    }]
                    selector: _labels
                }
            }
            _deployment: {
                apiVersion: "apps/v1"
                kind:       "Deployment"
                metadata:   _metadata
                spec: {
                    selector: matchLabels: {
                        app: _labels.app
                    }
                    template: {
                        metadata: labels: _labels
                        spec: {
                            containers: [{
                                name:  string | *"simple-app"
                                image: string | *"docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0"
                                env: [{
                                    name:  string | *"HELLO_MSG"
                                    value: string | *"hello world"
                                }]
                            }]
                        }
                    }
                }
            }
  template:
  - cue:
      valuesFrom:
      - configMapRef:
          name: cue-values
  deploy:
  - kapp: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cue-values
data:
  values.cue: |
    package main

    _labels: {
        app: "hello-cue"
    }

    _metadata: {
        name:      _labels.app
        namespace: "default"
    }
    _deployment: {
        spec: {
            template: {
                spec: {
                    containers: [{
                        name: "hello-cue"
                        env: [{
                            value: "hello cue"
                        }]
                    }]
                }
            }
        }
    }
