apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cue-app
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - inline:
      paths:
        values.cue: |
          package main

          _helloMsg: "stranger"
          _svcPort:  80
          _appPort:  80
          _labels: "simple-app": ""
        app.cue: |
          package main

          apiVersion: "v1"
          kind: "List"
          items: [_service, _deployment]

          _service: {
              apiVersion: "v1"
              kind:       "Service"
              metadata: {
                  namespace: "default"
                  name:      "simple-app"
              }
              spec: {
                  ports: [{
                      port:       _svcPort
                      targetPort: _appPort
                  }]
                  selector: _labels
              }
          }
          _deployment: {
              apiVersion: "apps/v1"
              kind:       "Deployment"
              metadata: {
                  namespace: "default"
                  name:      "simple-app"
              }
              spec: {
                  selector: matchLabels: _labels
                  template: {
                      metadata: labels: _labels
                      spec: {
                          containers: [{
                              name:  "simple-app"
                              image: "docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0"
                              env: [{
                                  name:  "HELLO_MSG"
                                  value: _helloMsg
                              }]
                          }]
                      }
                  }
              }
          }
  template:
  - cue: {}
  deploy:
  - kapp: {}
