---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: istio
  namespace: default
  annotations:
    kapp.k14s.io/change-group: istio
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - http:
      url: https://github.com/vmware-tanzu/carvel-kapp/archive/develop.zip
      subPath: carvel-kapp-develop/examples/istio-v1.4.0
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp: {}
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: knative
  namespace: default
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting istio"
    kapp.k14s.io/change-rule.1: "delete before deleting istio"
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - http:
      url: https://github.com/vmware-tanzu/carvel-kapp/archive/develop.zip
      subPath: carvel-kapp-develop/examples/knative-v0.10.0
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp: {}
