apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  serviceAccountName: simple-app-sa
  fetch:
  - http:
      url: https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip
      subPath: k8s-simple-app-example-master/config-step-2-template
  template:
  - ytt: {}
  deploy:
  - kapp: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-app-sa
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simple-app-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps", "services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simple-app-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: simple-app-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simple-app-role
