---
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: pkg2.test.carvel.dev
  # cluster scoped
spec:
  displayName: "Test Package in repo"
  description: "Package used for testing"
---
apiVersion: package.carvel.dev/v1alpha1
kind: PackageVersion
metadata:
  name: pkg2.test.carvel.dev.1.0.0
  # cluster scoped
spec:
  packageName: pkg2.test.carvel.dev
  version: 1.0.0
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/k14s/k8s-simple-app-example
          ref: origin/develop
          subPath: config-step-2-template
      template:
      - ytt: {}
      deploy:
      - kapp: {}
---
apiVersion: package.carvel.dev/v1alpha1
kind: PackageVersion
metadata:
  name: pkg2.test.carvel.dev.2.0.0
  # cluster scoped
spec:
  packageName: pkg2.test.carvel.dev
  version: 2.0.0
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/k14s/k8s-simple-app-example
          ref: origin/develop
      template:
      - ytt:
          paths:
          - config-step-2-template
          - config-step-2a-overlays
      deploy:
      - kapp: {}
