---
apiVersion: package.carvel.dev/v1alpha1
kind: PackageVersion
metadata:
  name: simple-app.corp.com.2.0.0
  # cluster scoped
spec:
  packageName: simple-app.corp.com
  # In this new version of the package, we are including some overlays
  # which will increase the pod count for the simple app.
  version: 2.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: k8slt/kctrl-example-pkg:v2.0.0
      template:
      - ytt:
          paths:
          - config-step-2-template
          - config-step-2a-overlays
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
