apiVersion: kapp.k14s.io/v1alpha1
kind: Config

# knative-serving-admin ClusterRole get aggregated by the RBAC controller
rebaseRules:
- type: copy
  sources: [existing, new]
  path: [rules]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      name: knative-serving-admin
      kind: ClusterRole

- path: [webhooks, {allIndexes: true}, rules]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration
  - apiVersionKindMatcher:
      apiVersion: admissionregistration.k8s.io/v1beta1
      kind: ValidatingWebhookConfiguration
