name: dependency-updater

on:
  push:
    branches:
      - dependency-updater
      
jobs:
  check-for-releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: ['ytt', 'kapp', 'kbld', 'imgpkg', 'vendir']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Current Release Version
        id: current-version
        run: |
          echo ::set-output name=version::$(grep "${{ matrix.tool }}_version=v" hack/install-deps.sh | cut -d "=" -f2)
      - name: Get Latest Release Version
        id: latest-version
        run: |
          echo ::set-output name=version::$(curl -sL https://api.github.com/repos/vmware-tanzu/carvel-${{ matrix.tool }}/releases/latest | jq -r '.tag_name')
      - name: Update Versions
        if: ${{ steps.current-version.outputs.version }} == ${{ steps.latest-version.outputs.version }}
        run: |
          set -xeou pipefail
          sed -i '/${{ matrix.tool }}_version/s/${{ steps.current-version.outputs.version }}/${{ steps.latest-version.outputs.version }}/g' ./hack/install-deps.sh
          
          old_darwin_amd64_sha=$(yq eval '.${{ matrix.tool }}.checksum_darwin' ./hack/dependencies.yml) 
          old_linux_amd64_sha=$(yq eval '.${{ matrix.tool }}.checksum_linux' ./hack/dependencies.yml)
          
          release_notes=$(curl https://api.github.com/repos/vmware-tanzu/carvel-${{ matrix.tool }}/releases/latest | jq .body -r)
          new_darwin_amd64_sha=$( echo "$release_notes" | grep ${{ matrix.tool }}-darwin-amd64 | awk '{print $1;}')
          new_linux_amd64_sha=$( echo "$release_notes" | grep ${{ matrix.tool }}-linux-amd64 | awk '{print $1;}')
          
          sed -i 's//${{ steps.latest-version.outputs.version }}/g' ./hack/install-deps.sh
          
          echo "old sha: $old_darwin_amd64_sha"
          echo "new sha: $darwin_amd64_sha"
          
          echo "old sha: $old_linux_amd64_sha"
          echo "new sha: $linux_amd64_sha"
          
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3.12.0
#         with:
#           commit-message: Bump ${{ matrix.tool }} to ${{ steps.latest-version.outputs.version }}
#           title: Bump ${{ matrix.tool }} to ${{ steps.latest-version.outputs.version }}
#           delete-branch: true
#           body: |
#             Auto-generated by https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          
         
